language: java

sudo: false

dist: trusty

jdk:
- openjdk8

after_success:
- bash <(curl -s https://codecov.io/bash)


addons:
  sonarcloud:
    organization: "riguron"
    token:
      secure: "hGjXvCrea8wb4P2SeEjMQnRuKy+mARiy3h0ezHdo1jOEi59maL25T5gAMsRSIofRjUuM+/wzP4n7Tf33IvpGewLNznZKwkb3p3ggrG1AjvzFLFs+DhjtTsAj84hmFkO4g3PWy4izttZNcO73t67+pIVfB5QmRfWVfj8mFdGKkHzhAp4p66K9qPG1jZaSI/L89oEWI2NxpIGKRzQ9tq5lEmSZqUDOHfcqZeUoT6ARqgYqwdcwwS/Yv4ol2gxAK9NVgUqJQjN5wNY/KM4PEl82n0XRWnvxDWf7VWvpB2ZJpyGSmTn+REFd+P6H/FunbTlVLorFzhL/dtdIVSiaWF5fgLwlvbmRDfzWh5jcqajZCgvc3CKP0LydLGOBePgNwc6jKsca5RUWqDeF4rlSzktWipPX38DonFRkAltKa8bW2kuQzV5+hRAhSAdWofFuU0o6FLHjxIiuBjLv/qhNU3x54TSGqz/MKhyUfRwSQeVmjxHdGQi2Q16g/FY3qvJiXi83li0NKtr6tuxTzeDVC6umCzPBZh+WRc3uBrApwyERTyIoBOqD4piTGkYGzJMLAhFyDIPfMM3V5lUihqfyKER3syHf72ZQ9qNdCD/QMWKAiTE8vuuvFvIsWkolNvGETlG83EskT/JyA3p0tRNR/bG+joHnc974Qqfrf7dR98r4v1E="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=riguron_Mocks
